name: Publish Storybook build to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  gh-pages:
    name: Publishing with gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Setup Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.1'

      - name: Clean install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
